-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.attendance (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  owner_id uuid NOT NULL,
  student_id uuid NOT NULL,
  class_id uuid NOT NULL,
  date date NOT NULL,
  status text NOT NULL CHECK (status = ANY (ARRAY['presente'::text, 'falta'::text, 'falta_justificada'::text, 'atestado'::text])),
  recorded_by uuid,
  recorded_at timestamp with time zone NOT NULL DEFAULT now(),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT attendance_pkey PRIMARY KEY (id),
  CONSTRAINT attendance_owner_id_fkey FOREIGN KEY (owner_id) REFERENCES auth.users(id),
  CONSTRAINT attendance_student_id_fkey FOREIGN KEY (student_id) REFERENCES public.students(id),
  CONSTRAINT attendance_class_id_fkey FOREIGN KEY (class_id) REFERENCES public.classes(id),
  CONSTRAINT attendance_recorded_by_fkey FOREIGN KEY (recorded_by) REFERENCES auth.users(id)
);
CREATE TABLE public.authorized_emails (
  email text NOT NULL,
  role text DEFAULT 'professor'::text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT authorized_emails_pkey PRIMARY KEY (email)
);
CREATE TABLE public.classes (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  owner_id uuid NOT NULL,
  name text NOT NULL,
  series text NOT NULL,
  letter text,
  course text,
  director_id uuid,
  director_email text,
  active boolean NOT NULL DEFAULT true,
  start_year smallint,
  current_year smallint,
  start_year_date date,
  start_calendar_year integer,
  end_calendar_year integer,
  archived boolean NOT NULL DEFAULT false,
  archived_at timestamp with time zone,
  archived_reason text,
  template_id uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT classes_pkey PRIMARY KEY (id),
  CONSTRAINT classes_owner_id_fkey FOREIGN KEY (owner_id) REFERENCES auth.users(id),
  CONSTRAINT classes_director_id_fkey FOREIGN KEY (director_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.certificate_events (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  owner_id uuid NOT NULL,
  created_by_name text NOT NULL,
  title text NOT NULL,
  certificate_type text NOT NULL CHECK (certificate_type = ANY (ARRAY['monitoria'::text, 'destaque'::text, 'evento_participacao'::text, 'evento_organizacao'::text])),
  class_id uuid,
  class_name_snapshot text NOT NULL,
  school_year smallint NOT NULL CHECK (school_year >= 1 AND school_year <= 3),
  period_mode text NOT NULL CHECK (period_mode = ANY (ARRAY['quarters'::text, 'annual'::text])),
  selected_quarters ARRAY NOT NULL DEFAULT '{}'::text[],
  period_label text NOT NULL,
  reference_type text CHECK (reference_type = ANY (ARRAY['subject'::text, 'area'::text])),
  reference_value text,
  reference_label text,
  base_text text NOT NULL,
  teacher_name text,
  director_name text,
  signature_mode text NOT NULL DEFAULT 'digital_cursive'::text CHECK (signature_mode = ANY (ARRAY['digital_cursive'::text, 'physical_print'::text])),
  type_meta jsonb NOT NULL DEFAULT '{}'::jsonb,
  students_count integer NOT NULL DEFAULT 0 CHECK (students_count >= 0),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT certificate_events_pkey PRIMARY KEY (id),
  CONSTRAINT certificate_events_owner_id_fkey FOREIGN KEY (owner_id) REFERENCES auth.users(id),
  CONSTRAINT certificate_events_class_id_fkey FOREIGN KEY (class_id) REFERENCES public.classes(id) ON DELETE SET NULL
);
CREATE TABLE public.certificate_event_students (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  owner_id uuid NOT NULL,
  certificate_event_id uuid NOT NULL,
  student_id uuid,
  student_name_snapshot text NOT NULL,
  text_override text,
  highlight_status text CHECK (highlight_status = ANY (ARRAY['confirmed'::text, 'pending'::text])),
  highlight_average numeric,
  verification_code text NOT NULL DEFAULT upper(replace((gen_random_uuid())::text, '-'::text, ''::text)),
  verification_status text NOT NULL DEFAULT 'valid'::text CHECK (verification_status = ANY (ARRAY['valid'::text, 'revoked'::text])),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT certificate_event_students_pkey PRIMARY KEY (id),
  CONSTRAINT certificate_event_students_owner_id_fkey FOREIGN KEY (owner_id) REFERENCES auth.users(id),
  CONSTRAINT certificate_event_students_certificate_event_id_fkey FOREIGN KEY (certificate_event_id) REFERENCES public.certificate_events(id) ON DELETE CASCADE,
  CONSTRAINT certificate_event_students_student_id_fkey FOREIGN KEY (student_id) REFERENCES public.students(id) ON DELETE SET NULL
);
CREATE TABLE public.comments (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  owner_id uuid NOT NULL,
  incident_id uuid NOT NULL,
  user_id uuid,
  user_name text,
  text text NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT comments_pkey PRIMARY KEY (id),
  CONSTRAINT comments_owner_id_fkey FOREIGN KEY (owner_id) REFERENCES auth.users(id),
  CONSTRAINT comments_incident_id_fkey FOREIGN KEY (incident_id) REFERENCES public.incidents(id),
  CONSTRAINT comments_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.external_assessments (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  student_id uuid NOT NULL,
  assessment_type text NOT NULL,
  assessment_name text NOT NULL,
  subject text,
  score numeric NOT NULL,
  max_score numeric NOT NULL DEFAULT 100,
  proficiency_level text,
  applied_date date,
  temporal_position jsonb DEFAULT '{}'::jsonb,
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  grade_year integer,
  quarter text,
  school_level text,
  CONSTRAINT external_assessments_pkey PRIMARY KEY (id),
  CONSTRAINT external_assessments_student_id_fkey FOREIGN KEY (student_id) REFERENCES public.students(id)
);
CREATE TABLE public.follow_ups (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  owner_id uuid NOT NULL,
  incident_id uuid NOT NULL,
  type text NOT NULL CHECK (type = ANY (ARRAY['conversa_individual'::text, 'conversa_pais'::text, 'situacoes_diversas'::text])),
  date date NOT NULL,
  suspension_applied boolean NOT NULL DEFAULT false,
  responsavel text,
  motivo text,
  providencias text,
  assuntos_tratados text,
  encaminhamentos text,
  disciplina text,
  tipo_situacao text,
  descricao_situacao text,
  nome_responsavel_pai text,
  grau_parentesco text,
  created_by uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT follow_ups_pkey PRIMARY KEY (id),
  CONSTRAINT follow_ups_owner_id_fkey FOREIGN KEY (owner_id) REFERENCES auth.users(id),
  CONSTRAINT follow_ups_incident_id_fkey FOREIGN KEY (incident_id) REFERENCES public.incidents(id),
  CONSTRAINT follow_ups_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id)
);
CREATE TABLE public.grades (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  owner_id uuid NOT NULL,
  student_id uuid NOT NULL,
  class_id uuid NOT NULL,
  subject text NOT NULL,
  quarter text NOT NULL,
  school_year smallint NOT NULL DEFAULT 1 CHECK (school_year >= 1 AND school_year <= 3),
  grade numeric NOT NULL CHECK (grade >= 0::numeric AND grade <= 10::numeric),
  observation text,
  recorded_at timestamp with time zone NOT NULL DEFAULT now(),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT grades_pkey PRIMARY KEY (id),
  CONSTRAINT grades_owner_id_fkey FOREIGN KEY (owner_id) REFERENCES auth.users(id),
  CONSTRAINT grades_student_id_fkey FOREIGN KEY (student_id) REFERENCES public.students(id),
  CONSTRAINT grades_class_id_fkey FOREIGN KEY (class_id) REFERENCES public.classes(id)
);
CREATE TABLE public.historical_grades (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  student_id uuid NOT NULL,
  school_level text NOT NULL DEFAULT 'fundamental'::text,
  grade_year integer NOT NULL,
  subject text NOT NULL,
  quarter text NOT NULL,
  grade numeric NOT NULL CHECK (grade >= 0::numeric AND grade <= 10::numeric),
  school_name text,
  calendar_year integer NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT historical_grades_pkey PRIMARY KEY (id),
  CONSTRAINT historical_grades_student_id_fkey FOREIGN KEY (student_id) REFERENCES public.students(id)
);
CREATE TABLE public.incidents (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  owner_id uuid NOT NULL,
  class_id uuid NOT NULL,
  date date NOT NULL,
  student_ids ARRAY NOT NULL DEFAULT '{}'::uuid[],
  episodes ARRAY NOT NULL DEFAULT '{}'::text[],
  calculated_severity text NOT NULL CHECK (calculated_severity = ANY (ARRAY['leve'::text, 'intermediaria'::text, 'grave'::text, 'gravissima'::text])),
  final_severity text NOT NULL CHECK (final_severity = ANY (ARRAY['leve'::text, 'intermediaria'::text, 'grave'::text, 'gravissima'::text])),
  severity_override_reason text,
  description text,
  actions text,
  suggested_action text,
  status text NOT NULL CHECK (status = ANY (ARRAY['aberta'::text, 'acompanhamento'::text, 'resolvida'::text])),
  validated_by uuid,
  validated_at timestamp with time zone,
  disciplinary_reset_applied boolean NOT NULL DEFAULT false,
  disciplinary_reset_at date,
  disciplinary_reset_inferred boolean NOT NULL DEFAULT false,
  created_by uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT incidents_pkey PRIMARY KEY (id),
  CONSTRAINT incidents_owner_id_fkey FOREIGN KEY (owner_id) REFERENCES auth.users(id),
  CONSTRAINT incidents_class_id_fkey FOREIGN KEY (class_id) REFERENCES public.classes(id),
  CONSTRAINT incidents_validated_by_fkey FOREIGN KEY (validated_by) REFERENCES auth.users(id),
  CONSTRAINT incidents_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id)
);
CREATE TABLE public.professional_subject_templates (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  owner_id uuid NOT NULL,
  name text NOT NULL,
  course text NOT NULL,
  subjects_by_year jsonb NOT NULL DEFAULT '[]'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT professional_subject_templates_pkey PRIMARY KEY (id),
  CONSTRAINT professional_subject_templates_owner_id_fkey FOREIGN KEY (owner_id) REFERENCES auth.users(id)
);
CREATE TABLE public.professional_subjects (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  owner_id uuid NOT NULL,
  class_id uuid NOT NULL,
  subject text NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT professional_subjects_pkey PRIMARY KEY (id),
  CONSTRAINT professional_subjects_owner_id_fkey FOREIGN KEY (owner_id) REFERENCES auth.users(id),
  CONSTRAINT professional_subjects_class_id_fkey FOREIGN KEY (class_id) REFERENCES public.classes(id)
);
CREATE TABLE public.profiles (
  id uuid NOT NULL,
  name text NOT NULL,
  role text NOT NULL DEFAULT 'diretor'::text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT profiles_pkey PRIMARY KEY (id),
  CONSTRAINT profiles_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id)
);
CREATE TABLE public.school_config (
  id uuid NOT NULL DEFAULT '00000000-0000-0000-0000-000000000000'::uuid CHECK (id = '00000000-0000-0000-0000-000000000000'::uuid),
  school_name text NOT NULL DEFAULT 'INSTITUIÇÃO DE ENSINO'::text,
  address text,
  city text,
  state text,
  cep text,
  phone text,
  email text,
  director_name text,
  inep text,
  logo_base64 text,
  signature_base64 text,
  theme_color text DEFAULT '#0F172A'::text,
  additional_info text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT school_config_pkey PRIMARY KEY (id)
);
CREATE TABLE public.students (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  owner_id uuid NOT NULL,
  class_id uuid NOT NULL,
  name text NOT NULL,
  birth_date date NOT NULL,
  gender text NOT NULL,
  enrollment text,
  census_id text,
  cpf text,
  rg text,
  photo_url text,
  status text NOT NULL DEFAULT 'active'::text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT students_pkey PRIMARY KEY (id),
  CONSTRAINT students_owner_id_fkey FOREIGN KEY (owner_id) REFERENCES auth.users(id),
  CONSTRAINT students_class_id_fkey FOREIGN KEY (class_id) REFERENCES public.classes(id)
);

CREATE INDEX IF NOT EXISTS incidents_disciplinary_reset_idx
ON public.incidents (disciplinary_reset_applied, disciplinary_reset_at);
